# -----
# Site
# -----

title: Ssup2 Blog
url: https://ssup2.github.io
baseurl:
google_analytics_key: UA-77446431-3
show_full_navigation: true

# -----
# Build
# -----

permalink: pretty

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
    categories:
      output: true

    docs:
      title: Documentation
      permalink: /:path/
      output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article

# -----
# seo-tag
# -----

title: Ssup2's Blog
description: Ssup2's personal blog to record my knowledge
url: https://ssup2.github.io
logo: /siteicon.png
author: Ssup2
social:
  name: Ssup2
  links:
    - https://ssup2.github.io
