---
title: Ssup2 Blog
timezone: UTC
collections:
  category:
    title: Category
    output: true
  docs:
    title: Documentation
    output: true
    permalink: "/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: docs
  values:
    seo:
      type: Article
    _comments:
      category: Group navigation links with this field
      order: Used to sort links in the navigation
- scope:
    path: ''
    type: posts
  values:
    _comments:
      type: Marks the impact of this release
url: https://ssup2.github.io
baseurl: 
google_analytics_key: 
show_full_navigation: true
logo: "/siteicon.png"
description: Product documentation template for Jekyll.
author:
  name: Ssup2
  email: supsup5642@naver.com
social:
  name: Ssup2 Blog
  links:
  - https://ssup2.github.io
permalink: pretty
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
