# -----
# Site
# -----

title: Ssup2 Blog
url: "https://ssup2.github.io"
baseurl:
google_analytics_key: UA-77446431-3
show_full_navigation: true

# -----
# Build
# -----

permalink: pretty

gems:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
    category:
      output: true

    docs:
      title: Documentation
      permalink: /:path/
      output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article

# -----
# seo-tag
# -----

logo: /siteicon.png
description: Product documentation template for Jekyll.
author:
  name: Ssup2
  email: supsup5642@naver.com
social:
  name: Ssup2 Blog
  links:
    - https://ssup2.github.io
