# Site

title: Ssup2 Blog
url: "https://ssup2.github.io"
baseurl:
google_analytics_key:
show_full_navigation: true

# Mark Down
markdown: kramdown
kramdown:
    auto_ids:       true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   lsquo,rsquo,ldquo,rdquo
    input:          GFM
    hard_wrap:      false
    footnote_nr:    1

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product documentation template for Jekyll.
author:
  name: Ssup2
  email: supsup5642@naver.com
social:
  name: Ssup2 Blog
  links:
    - https://ssup2.github.io

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
    category:
      output: true

    docs:
      title: Documentation
      permalink: /:path/
      output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article

